# Classification of samples into cancerous and non cancerous using Random forest and ANOVA F - value as a data reduction technique

In [1]:
import numpy as np
import pandas as pd

Read the cancer data into Pandas dataframe (Data is already split into x_train, y_train, x_test and y_test)

In [2]:
data_names = pd.read_csv("/home/seeraja/anaconda3/iitgn/datasets-master/cancer subtype classification datasetspart01/head_neck_2/methylation/methyl_x_train.csv", low_memory=False)

In [3]:
data_names

,Unnamed: 0,Idx,AAAS-M,AACS-M,AADAT-M,AAED1-M,AAGAB-M,AAK1-M,AAMDC-M,AAMP-M,...,ZSWIM7-M,ZSWIM8-M,ZW10-M,ZWINT-M,ZXDC-M,ZYG11A-M,ZYG11B-M,ZYX-M,ZZEF1-M,ZZZ3-M
0,28,C3N-03490-N,0.032548,0.019644,0.031529,0.026623,0.023774,0.022213,0.021022,0.024074,...,0.052558,0.016148,0.020244,0.034220,0.030853,0.016933,0.145074,0.023474,0.020991,0.023185
1,99,C3N-04276,0.026822,0.015984,0.016237,0.022432,0.021905,0.019470,0.024963,0.021150,...,0.060409,0.013859,0.022262,0.032040,0.036064,0.328353,0.021171,0.018502,0.020986,0.027803
2,23,C3N-00498,0.023308,0.014592,0.080124,0.024676,0.019475,0.022044,0.022564,0.019460,...,0.067604,0.012299,0.020851,0.038137,0.064035,0.018555,0.060874,0.016466,0.021761,0.030849
3,33,C3N-01620,0.023346,0.014332,0.021047,0.022531,0.019249,0.022003,0.014218,0.021051,...,0.040795,0.010592,0.020974,0.035922,0.025646,0.298594,0.096735,0.014568,0.022528,0.024099
4,86,C3N-03785,0.029347,0.015822,0.017042,0.025958,0.017184,0.020531,0.019615,0.020664,...,0.035241,0.015076,0.021337,0.032470,0.021827,0.012323,0.014445,0.017886,0.018822,0.024582
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,21,C3N-02925-N,0.029961,0.017323,0.012091,0.022243,0.021372,0.022003,0.019497,0.021648,...,0.041921,0.016293,0.018935,0.028977,0.026288,0.014124,0.058720,0.015568,0.018142,0.024336
111,33,C3N-03878-N,0.037367,0.025722,0.065418,0.028280,0.022520,0.028332,0.029827,0.022756,...,0.052322,0.018835,0.022897,0.037415,0.031051,0.020243,0.082134,0.022863,0.022130,0.033970
112,18,C3N-00297,0.027386,0.016685,0.073422,0.021369,0.024767,0.024152,0.022124,0.022584,...,0.043808,0.014066,0.027487,0.038417,0.040538,0.024058,0.020451,0.025344,0.023935,0.034050
113,34,C3N-03888-N,0.029970,0.018168,0.017234,0.028162,0.026124,0.022844,0.022871,0.022608,...,0.051360,0.014977,0.021208,0.031242,0.023896,0.013649,0.077867,0.019447,0.020155,0.029925
114,12,C3N-01754-N,0.028356,0.017578,0.014578,0.022787,0.020774,0.020728,0.018687,0.020901,...,0.034896,0.015195,0.020938,0.035260,0.025985,0.014649,0.014206,0.018669,0.019855,0.025870

In [4]:
data = pd.read_csv("/home/seeraja/anaconda3/iitgn/datasets-master/cancer subtype classification datasetspart01/head_neck_2/methylation/methyl_after_zero_variance.csv", low_memory=False)

In [5]:
data

,Unnamed: 0,AAAS-M,AACS-M,AADAT-M,AAED1-M,AAGAB-M,AAK1-M,AAMDC-M,AAMP-M,AANAT-M,...,ZSWIM7-M,ZSWIM8-M,ZW10-M,ZWINT-M,ZXDC-M,ZYG11A-M,ZYG11B-M,ZYX-M,ZZEF1-M,ZZZ3-M
0,0,0.032548,0.019644,0.031529,0.026623,0.023774,0.022213,0.021022,0.024074,0.022467,...,0.052558,0.016148,0.020244,0.034220,0.030853,0.016933,0.145074,0.023474,0.020991,0.023185
1,1,0.026822,0.015984,0.016237,0.022432,0.021905,0.019470,0.024963,0.021150,0.014992,...,0.060409,0.013859,0.022262,0.032040,0.036064,0.328353,0.021171,0.018502,0.020986,0.027803
2,2,0.023308,0.014592,0.080124,0.024676,0.019475,0.022044,0.022564,0.019460,0.016609,...,0.067604,0.012299,0.020851,0.038137,0.064035,0.018555,0.060874,0.016466,0.021761,0.030849
3,3,0.023346,0.014332,0.021047,0.022531,0.019249,0.022003,0.014218,0.021051,0.012886,...,0.040795,0.010592,0.020974,0.035922,0.025646,0.298594,0.096735,0.014568,0.022528,0.024099
4,4,0.029347,0.015822,0.017042,0.025958,0.017184,0.020531,0.019615,0.020664,0.019219,...,0.035241,0.015076,0.021337,0.032470,0.021827,0.012323,0.014445,0.017886,0.018822,0.024582
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,110,0.029961,0.017323,0.012091,0.022243,0.021372,0.022003,0.019497,0.021648,0.024316,...,0.041921,0.016293,0.018935,0.028977,0.026288,0.014124,0.058720,0.015568,0.018142,0.024336
111,111,0.037367,0.025722,0.065418,0.028280,0.022520,0.028332,0.029827,0.022756,0.023088,...,0.052322,0.018835,0.022897,0.037415,0.031051,0.020243,0.082134,0.022863,0.022130,0.033970
112,112,0.027386,0.016685,0.073422,0.021369,0.024767,0.024152,0.022124,0.022584,0.017363,...,0.043808,0.014066,0.027487,0.038417,0.040538,0.024058,0.020451,0.025344,0.023935,0.034050
113,113,0.029970,0.018168,0.017234,0.028162,0.026124,0.022844,0.022871,0.022608,0.020652,...,0.051360,0.014977,0.021208,0.031242,0.023896,0.013649,0.077867,0.019447,0.020155,0.029925
114,114,0.028356,0.017578,0.014578,0.022787,0.020774,0.020728,0.018687,0.020901,0.017580,...,0.034896,0.015195,0.020938,0.035260,0.025985,0.014649,0.014206,0.018669,0.019855,0.025870

In [6]:
data=data.drop(columns=["Unnamed: 0"])

In [7]:
data

,AAAS-M,AACS-M,AADAT-M,AAED1-M,AAGAB-M,AAK1-M,AAMDC-M,AAMP-M,AANAT-M,AAR2-M,...,ZSWIM7-M,ZSWIM8-M,ZW10-M,ZWINT-M,ZXDC-M,ZYG11A-M,ZYG11B-M,ZYX-M,ZZEF1-M,ZZZ3-M
0,0.032548,0.019644,0.031529,0.026623,0.023774,0.022213,0.021022,0.024074,0.022467,0.015985,...,0.052558,0.016148,0.020244,0.034220,0.030853,0.016933,0.145074,0.023474,0.020991,0.023185
1,0.026822,0.015984,0.016237,0.022432,0.021905,0.019470,0.024963,0.021150,0.014992,0.018018,...,0.060409,0.013859,0.022262,0.032040,0.036064,0.328353,0.021171,0.018502,0.020986,0.027803
2,0.023308,0.014592,0.080124,0.024676,0.019475,0.022044,0.022564,0.019460,0.016609,0.014199,...,0.067604,0.012299,0.020851,0.038137,0.064035,0.018555,0.060874,0.016466,0.021761,0.030849
3,0.023346,0.014332,0.021047,0.022531,0.019249,0.022003,0.014218,0.021051,0.012886,0.010666,...,0.040795,0.010592,0.020974,0.035922,0.025646,0.298594,0.096735,0.014568,0.022528,0.024099
4,0.029347,0.015822,0.017042,0.025958,0.017184,0.020531,0.019615,0.020664,0.019219,0.012792,...,0.035241,0.015076,0.021337,0.032470,0.021827,0.012323,0.014445,0.017886,0.018822,0.024582
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,0.029961,0.017323,0.012091,0.022243,0.021372,0.022003,0.019497,0.021648,0.024316,0.017585,...,0.041921,0.016293,0.018935,0.028977,0.026288,0.014124,0.058720,0.015568,0.018142,0.024336
111,0.037367,0.025722,0.065418,0.028280,0.022520,0.028332,0.029827,0.022756,0.023088,0.034573,...,0.052322,0.018835,0.022897,0.037415,0.031051,0.020243,0.082134,0.022863,0.022130,0.033970
112,0.027386,0.016685,0.073422,0.021369,0.024767,0.024152,0.022124,0.022584,0.017363,0.017955,...,0.043808,0.014066,0.027487,0.038417,0.040538,0.024058,0.020451,0.025344,0.023935,0.034050
113,0.029970,0.018168,0.017234,0.028162,0.026124,0.022844,0.022871,0.022608,0.020652,0.015272,...,0.051360,0.014977,0.021208,0.031242,0.023896,0.013649,0.077867,0.019447,0.020155,0.029925
114,0.028356,0.017578,0.014578,0.022787,0.020774,0.020728,0.018687,0.020901,0.017580,0.012256,...,0.034896,0.015195,0.020938,0.035260,0.025985,0.014649,0.014206,0.018669,0.019855,0.025870

Getting the labels

In [10]:
data_y = pd.read_csv("/home/seeraja/anaconda3/iitgn/datasets-master/cancer subtype classification datasetspart01/head_neck_2/methylation/methyl_y_train.csv", low_memory=False)

In [11]:
data_y

     Unnamed: 0   0
0             0  NC
1             1   C
2             2   C
3             3   C
4             4   C
..          ...  ..
110         110  NC
111         111  NC
112         112   C
113         113  NC
114         114  NC

[115 rows x 2 columns]

Convert to numpy array

In [12]:
arr_y=data_y.values

In [13]:
y=arr_y[:,1]

In [14]:
y

array(['NC', 'C', 'C', 'C', 'C', 'NC', 'C', 'NC', 'NC', 'C', 'C', 'C',
       'C', 'C', 'C', 'C', 'C', 'NC', 'C', 'C', 'NC', 'C', 'C', 'C', 'NC',
       'C', 'C', 'C', 'C', 'NC', 'C', 'C', 'C', 'C', 'NC', 'C', 'C', 'C',
       'NC', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'NC', 'C', 'C', 'NC', 'C',
       'C', 'C', 'C', 'C', 'NC', 'NC', 'C', 'C', 'C', 'C', 'NC', 'C',
       'NC', 'C', 'NC', 'C', 'C', 'C', 'C', 'C', 'C', 'NC', 'C', 'NC',
       'NC', 'C', 'C', 'C', 'C', 'NC', 'C', 'C', 'C', 'C', 'C', 'NC', 'C',
       'C', 'C', 'C', 'C', 'C', 'NC', 'NC', 'C', 'C', 'C', 'C', 'C', 'C',
       'C', 'NC', 'C', 'C', 'NC', 'C', 'NC', 'C', 'NC', 'NC', 'NC', 'C',
       'NC', 'NC'], dtype=object)

In [15]:
y.size

115

# ANOVA F-value

Import SelectKBest to select the number of features and f_classif to calculate the AVOVA F-value score

In [16]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

In [17]:
# to get all features ranking
selector_f = SelectKBest(f_classif, k='all').fit(data,y)

Create a dataframe of the feature names and their ANOVA F-value scores

In [18]:
df_scores = pd.DataFrame(selector_f.scores_)
df_columns = pd.DataFrame(data.columns)
feature_scores = pd.concat([df_columns, df_scores],axis=1)
feature_scores.columns = ['Feature_Name','Score']

In [19]:
feature_scores

      Feature_Name     Score
0           AAAS-M  0.004128
1           AACS-M  0.285841
2          AADAT-M  4.405988
3          AAED1-M  2.394537
4          AAGAB-M  0.468068
...            ...       ...
13111     ZYG11A-M  4.155533
13112     ZYG11B-M  0.067845
13113        ZYX-M  0.965037
13114      ZZEF1-M  3.092451
13115       ZZZ3-M  0.708307

[13116 rows x 2 columns]

Rank the features according to their score

In [20]:
data_use=feature_scores.nlargest(13116,'Score')

In [21]:
data_use

      Feature_Name         Score
5063      HOXD12-M  1.726931e+02
9169       RGS22-M  1.677453e+02
2115        CHAT-M  1.528923e+02
12696     ZNF135-M  1.511970e+02
3748     FAM135B-M  1.495920e+02
...            ...           ...
8608       PRR5L-M  2.732179e-07
5358       IP6K1-M  1.253009e-07
1375    C1orf145-M  1.200494e-07
10847       STYX-M  9.251063e-08
6777      MRPS27-M  2.931775e-10

[13116 rows x 2 columns]

In [ ]:
Save the rankings to csv file for further analysis

In [22]:
data_use.to_csv("methyl_fanova_feature_ranking_new.csv")